Basics of Tensor

In [2]:
import torch

In [3]:
torch.empty(size = (3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [4]:
device

'cuda'

In [5]:
torch.tensor([1,2,4],dtype=torch.float32 , device = device , requires_grad=True)

tensor([1., 2., 4.], device='cuda:0', requires_grad=True)

In [6]:
torch.ones(size=(3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
torch.arange(15)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
torch.linspace(start=1,end=10,steps=50)

tensor([ 1.0000,  1.1837,  1.3673,  1.5510,  1.7347,  1.9184,  2.1020,  2.2857,
         2.4694,  2.6531,  2.8367,  3.0204,  3.2041,  3.3878,  3.5714,  3.7551,
         3.9388,  4.1224,  4.3061,  4.4898,  4.6735,  4.8571,  5.0408,  5.2245,
         5.4082,  5.5918,  5.7755,  5.9592,  6.1429,  6.3265,  6.5102,  6.6939,
         6.8776,  7.0612,  7.2449,  7.4286,  7.6122,  7.7959,  7.9796,  8.1633,
         8.3469,  8.5306,  8.7143,  8.8980,  9.0816,  9.2653,  9.4490,  9.6327,
         9.8163, 10.0000])

In [11]:
torch.arange(15).view(3,5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [12]:
torch.arange(24).view(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [15]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [17]:
torch.tensor([1,2,3,4,5]).shape

torch.Size([5])

In [7]:
torch.tensor([1,2,3,4,5]).unsqueeze(axis=1)

tensor([[1],
        [2],
        [3],
        [4],
        [5]])

In [8]:
torch.tensor([1,2,3,4,5]).unsqueeze(axis=1).squeeze()

tensor([1, 2, 3, 4, 5])

Tensor operations

In [21]:
x=torch.ones(size=(3,4))
y=torch.ones(size=(3,4))*4

In [10]:
print(x)
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [13]:
z=torch.empty(size=(3,4))
torch.add(x,y,out=z)
z

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [40]:
z=torch.add(x,y)
z

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [41]:
z=x+y
z

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [42]:
x*y

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [43]:
torch.mul(x,y)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [14]:
y=torch.ones(size=(4,5))*4

In [15]:
y

tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])

In [16]:
torch.mm(x,y)

tensor([[16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.]])

In [17]:
torch.matmul(x,y)

tensor([[16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.]])

In [22]:
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
y

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [24]:
#x+=y
x.add_(y)
x

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])